# run pytests
image: python:3.7.8

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install pytest
          - python setup.py install
          - python -m pytest > tests/pytest.log
