{% set name = "miningpy" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}.{{ DEPLOY_TIME }}

source:
  git_url: ../

build:
  script_env:
    - DEPLOY_TIME
  noarch: python
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  always_include_files:
    - miningpy/VERSION

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ezdxf >=0.13.1
    - numpy
    - pandas
    - python >=3.6
    - pyvista
    - vtk >=8.0

test:
  imports:
    - miningpy

about:
  home: https://pypi.org/project/miningpy/
  summary: python tools for mining engineering
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - iainfullelove
