{% set name = "miningpy" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}.{{ DEPLOY_TIME }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python >=3.6
  host:
    - pip
    - python >=3.6
  run:
    - ezdxf >=0.13.1
    - numpy
    - pandas
    - python >=3.6
    - pyvista
    - vtk >=8.0

test:
  import:
    - miningpy

about:
  home: https://pypi.org/project/miningpy/
  summary: python tools for mining engineering
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - iainfullelove
