# Azure devops pipeline to test installing MiningPy from the nightly release from Anaconda Cloud


trigger: none

# no PR triggers
pr: none

variables:
  AZURE_PIPELINE: yes

schedules:
- cron: "0 14 * * *"
  displayName: Daily build
  branches:
    include:
    - master
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

jobs:
  - job: WindowsInstallCondaNightly
    pool:
      vmImage: 'windows-latest'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'

    steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    - script: |
        conda update conda
      displayName: Update conda

    - script: conda create --yes --quiet --name baseAnaconda python=$(python.version)
      displayName: Create Anaconda environment

    - script: |
        call activate baseAnaconda
        conda config --add channels conda-forge
      displayName: Add Conda Forge Channel

    - script: |
        call activate baseAnaconda
        conda install --yes --quiet --name baseAnaconda -c miningpy_nightly miningpy
      displayName: Install Nightly MiningPy

    - script: |
        call activate baseAnaconda
        python -c "import miningpy"
      displayName: Test MiningPy Import

