# Python package
# Test deploying package to PyPi

trigger: none

schedules:
- cron: "0 9 * * *"
  displayName: Daily build
  branches:
    include:
    - master
- cron: "0 7 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

jobs:
  - job: Test_PyPi_Deploy
    pool:
      vmImage: 'VS2017-Win2016'
    strategy:
      matrix:
        Python38:
          python.version: '3.8'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        addToPath: true
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install twine
        pip install wheel
      displayName: 'Install Deployment Requirements'

    - script: |
        set /p version=<miningpy/VERSION
        FOR /f %%a in ('WMIC OS GET LocalDateTime ^| find "."') DO set DTS=%%a
        set CUR_DATE=%DTS:~0,4%.%DTS:~4,2%.%DTS:~6,2%.%DTS:~8,4%
        python setup.py sdist bdist_wheel --testversion %version%.%CUR_DATE%
        twine check dist/*
      displayName: 'Build/Check Project'

    - script: |
        twine upload --repository testpypi dist/*
      displayName: 'Deploy Project'
      env:
        TWINE_USERNAME: $(twine.username)
        TWINE_PASSWORD: $(twine.password)
