# Azure devops pipeline to test installing MiningPy
# inside conda environment that already has VTK installed
# need to check/ensure there are not package conflicts

trigger: none

# no PR triggers
pr: none

schedules:
- cron: "0 8 * * *"
  displayName: Daily build
  branches:
    include:
    - master
- cron: "0 6 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

jobs:
  - job: WindowsCondaVtk_condaForge
    pool:
      vmImage: 'windows-latest'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'

    steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    - script: conda create --yes --quiet --name baseAnaconda python=$(python.version) anaconda
      displayName: Create Anaconda environment & Install packages

    - script: |
        call activate baseAnaconda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda install -c conda-forge vtk
        python -m pip install .
      displayName: Install miningpy package in conda env
