{% set name = "miningpy" %}
{% set version = "0.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  script: {{ PYTHON }} -m pip install .
  always_include_files:
    - miningpy/VERSION
    - miningpy/visualisation/ParaViewGlance.html
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - ezdxf >=1.0
    - pandas >=2.1
    - numpy >=1.26
    - python
    - pyvista >=0.43
    - pyqt5
    - pyvistaqt
    - vtk >=9.2
    - matplotlib-base

test:
  imports:
    - miningpy

about:
  home: https://pypi.org/project/miningpy/
  summary: python tools for mining engineering
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/miningpy/miningpy
  doc_url: https://miningpy.readthedocs.io

extra:
  recipe-maintainers:
    - iainfullelove
