# Azure devops pipeline to test building MiningPy using conda-build from the conda-recipe

on:
  workflow_dispatch:
  push:
    branches:
    - none
  schedule:
  - cron: '0 11 * * *'
  - cron: '0 9 * * 0'
jobs:
  WindowsBuildCondaRecipe:
    strategy:
      matrix:
        python.version:
        - "3.9"
    runs-on: windows-latest
    steps:
    - name: Check out Repository
      uses: actions/checkout@v3
    - name: Add conda to PATH
      run: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      shell: powershell
    - name: Update conda & conda-build
      run: |
        conda update conda
        conda install conda-build
        conda update conda-build
    - name: Purge Conda Build Dir
      run: conda build purge-all
    - name: Conda-Build Recipe & Test
      run: conda-build conda.recipe --no-anaconda-upload --channel conda-forge --python ${{ matrix.python.version }}
