# deploy package to PyPi

name: pypi-deploy
on:
  workflow_dispatch:
  push:
    branches:
    - none
  pull_request:
    branches:
    - none
jobs:
  PyPi_Deploy:
    strategy:
      matrix:
        python-version: ["3.10"]
    runs-on: windows-latest
    steps:
    - name: Check out Repository
      uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Deployment Requirements
      run: |
        python -m pip install --upgrade pip setuptools
        pip install twine
        pip install wheel
    - name: Build/Check Project
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Deploy Project
      run: twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_TWINE_PASSWORD }}
