# Python package
# Test deploying package to PyPi

on:
  workflow_dispatch:
  push:
    branches:
    - none
  pull_request:
    branches:
    - none
  schedule:
  - cron: '0 9 * * *'
jobs:
  Test_PyPi_Deploy:
    strategy:
      matrix:
        python-version: ["3.10"]
    runs-on: windows-latest
    steps:
    - name: Put current date into a variable
      run: |
        TIME=& Get-Date -format yyyy-MM-dd
        echo "TIME=TIME" >> $env:GITHUB_ENV
    - name: Check out Repository
      uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Deployment Requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install twine
        pip install wheel
    - name: Build/Check Project
      run: |
        set /p VERSION=<miningpy/VERSION
        python setup.py sdist bdist_wheel --testversion ${{ env.VERSION }}.${{ env.TIME }}
        twine check dist/*
    - name: Deploy Project
      run: twine upload --repository testpypi dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_TEST_TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TWINE_PASSWORD }}
