# test installing MiningPy from the test release to TestPyPi

name: pypi-test-install
on:
  workflow_dispatch:
  push:
    branches:
    - none
  pull_request:
    branches:
    - none
  schedule:
  - cron: '0 9 * * *'
jobs:
  Test_PyPi_Install:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    runs-on: windows-latest
    steps:
    - name: Check out Repository
      uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Nightly MiningPy
      run: pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ miningpy
    - name: Import miningpy
      run: |
        import miningpy
      shell: python

  